Repository i1ta/tripyle-frontend, pull requests merged in 2024-01, with the labels that each got.

#90 Refactor: 레이아웃 리팩토링
  pages/findTripyler/[tripylerId]/apply/index.tsx
  pages/findTripyler/[tripylerId]/edit/index.tsx
  src/components/addition/contact/contact.container.js
  src/components/addition/contact/contact.styles.js
  src/components/commons/Layout/Layout.tsx
  src/components/commons/Layout/NavBar.tsx
  src/components/commons/Layout/TopBtn.js
  src/components/tripyler/apply/applyForm.container.js
  src/components/tripyler/apply/applyForm.style.js
  src/components/tripyler/write/write.container.js
  yarn.lock
Labels: refactor

#91 Design: Contact페이지 리뉴얼
  src/components/addition/contact/contact.container.js
  src/components/addition/contact/contact.styles.js
Labels: design

#92 Design: 소개페이지 리뉴얼
  pages/addition/contact/index.js
  pages/addition/introduce/index.js
  pages/contact/index.tsx
  pages/introduce/index.tsx
  public/img/introduce1.svg
  public/img/introduce2.svg
  public/img/introduce3.svg
  src/components/addition/introduce/introduce.container.js
  src/components/addition/introduce/introduce.styles.js
  src/components/commons/Layout/NavBar.tsx
  src/components/contact/contact.container.tsx
  src/components/contact/contact.styles.ts
  src/components/introduce/Banners.tsx
  src/components/introduce/Faq.tsx
Labels: design

#93 Design: 후기 상세페이지 리뉴얼
  pages/findTripyler/[tripylerId]/index.tsx
  pages/review/[reviewId]/index.js
  pages/review/[reviewId]/index.tsx
  public/assets/logo.svg
  src/components/commons/Layout/Footer.tsx
  src/components/commons/Layout/NavBar.tsx
  src/components/detail/ApplyList.tsx
  src/components/detail/Banner.tsx
  src/components/detail/Comment.tsx
  src/components/detail/Images.tsx
  src/components/detail/MorePost.tsx
  src/components/detail/ReviewForm.tsx
  src/components/detail/TripylerForm.tsx
  src/components/detail/WithList.tsx
  src/components/review/detail/detail.container.js
  src/components/review/detail/detail.style.js
  src/components/review/main/main.container.js
  src/interfaces/detail.ts
  src/utils/format.ts
Labels: design

#94 Design: 메인페이지 반응형 적용
  pages/_app.tsx
  public/icon/close_menu.png
  public/icon/menu.png
  src/components/commons/Card/Main/FindCard/FindCard.js
  src/components/commons/Card/Main/ReviewCard/Review.js
  src/components/commons/Layout/Footer.tsx
  src/components/commons/Layout/NavBar.tsx
  src/components/commons/Layout/findTripylerBanner.tsx
  src/components/commons/MainBanner.tsx
  src/components/main/AdverBanner.tsx
  src/components/main/Main.container.js
  src/components/main/Main.styles.js
  src/components/main/ReviewBanner.tsx
  src/components/main/ReviewBox.tsx
  src/components/main/TripylerBox.tsx
  src/styles/globalStyles.js
  src/styles/theme.ts
Labels: style, design

#95 Design: 디바이스 별 글씨 크기 수정
  src/components/commons/Card/Main/FindCard/FindCard.js
  src/components/commons/Card/Main/ReviewCard/Review.js
  src/components/commons/MainBanner.tsx
  src/components/main/TripylerBox.tsx
  src/styles/globalStyles.js
Labels: design

#96 Refactor: 카카오 로그인 방식 수정
  .env
  .gitignore
  pages/auth/findId.js
  pages/auth/findPw.js
  pages/oauth/kakao.js
  src/OAuth/kakao.js
  src/components/auth/login/Login.container.js
  src/components/commons/Layout/SocialLogin.js/SocialLogin.js
  src/components/main/Main.container.js
Labels: refactor

#99 Refactor: 찾기작성페이지 api 컴포넌트화
  pages/findTripyler/write/index.tsx
  pages/review/write/index.tsx
  src/components/main/AdverBanner.tsx
  src/components/tripyler/write/write.container.js
  src/components/write/Banner.tsx
  src/components/write/Buttons.tsx
  src/components/write/IDModal.tsx
  src/components/write/PlaceModal.tsx
  src/components/write/TripylerStep1.tsx
  src/components/write/TripylerStep2.tsx
  src/components/write/TripylerStep3.tsx
  src/interfaces/write.ts
  src/styles/theme.ts
Labels: refactor

#100 refactor: 리뷰작성페이지 api 컴포넌트화
  pages/review/write/index.tsx
  src/components/write/Buttons.tsx
  src/components/write/ReviewStep1.tsx
  src/components/write/ReviewStep2.tsx
  src/components/write/ReviewStep3.tsx
  src/interfaces/write.ts
Labels: refactor

#101 Design: 마이페이지, 쪽지페이지 디자인 리뉴얼
  pages/review/[reviewId]/index.tsx
  src/components/auth/profile/Messenger/Messenger.container.js
  src/components/auth/profile/Messenger/Messengser.styles.js
  src/components/auth/profile/MyProfile/MyProfile.container.js
  src/components/auth/profile/MyProfile/MyProfile.styles.js
  src/components/auth/profile/Profile.container.js
  src/components/auth/profile/Profile.styles.js
  src/components/commons/Layout/NavBar.tsx
  src/components/detail/Comment.tsx
  src/components/profile/SideBar.tsx
  src/styles/globalStyles.js
Labels: design

#102 Design: 회원가입 리뉴얼
  src/components/auth/join/Join.container.js
  src/components/auth/join/Join.styles.js
  src/components/auth/profile/Messenger/Messengser.styles.js
  src/components/auth/profile/MyProfile/MyProfile.styles.js
  src/components/commons/Layout/NavBar.tsx
  src/components/detail/ReviewForm.tsx
Labels: design

#104 [Fix] 백 api 주소 변경 및 오류 수정
  pages/auth/signIn/index.js
  pages/findTripyler/write/index.tsx
  src/apis/index.ts
  src/components/admin/admin.container.js
  src/components/commons/Card/Main/FindCard/FindCard.js
  src/components/commons/Layout/NavBar.tsx
  src/components/commons/MainBanner.tsx
  src/components/commons/Modal/StyleModal.js
  src/components/detail/Comment.tsx
  src/components/main/Main.container.js
  src/components/tripyler/list/list.container.js
  src/components/write/Buttons.tsx
  src/components/write/TripylerStep1.tsx
Labels: fix

#105 Design: 반응형 추가
  .vscode/settings.json
  pages/404.tsx
  pages/auth/chnPw.js
  pages/auth/profile/collections.js
  pages/auth/profile/messenger.js
  pages/oauth/kakao.js
  public/img/bannerImg2.png
  public/img/platformBanner.png
  src/States/LoginState.js
  src/apis/index.ts
  src/components/auth/findInfo/ChnPw.container.js
  src/components/auth/findInfo/FindId.container.js
  src/components/auth/findInfo/FindPw.container.js
  src/components/auth/login/Login.container.js
  src/components/auth/profile/MyCollections/MyCollections.container.js
  src/components/auth/profile/MyCollections/MyCollections.styles.js
  src/components/auth/profile/MyProfile/MyProfile.container.js
  src/components/auth/profile/MyProfile/MyProfile.styles.js
  src/components/auth/profile/MyProfile/NotMyProfile.container.js
  src/components/auth/profile/MyProfile/NotMyProfile.styles.js
  src/components/auth/profile/Profile.container.js
  src/components/auth/profile/Profile.styles.js
  src/components/auth/profile/Triplog/Triplog.container.js
  src/components/auth/profile/Triplog/Triplog.styles.js
  src/components/commons/Card/Main/ReviewCard/ReviewMain.js
  src/components/commons/Card/MyCollections/ApplyCard.js
  src/components/commons/Card/MyCollections/FindCard.js
  src/components/commons/Card/MyCollections/FindListCard.js
  src/components/commons/Card/MyCollections/ReviewCard.js
  src/components/commons/Card/Triplog/FindCard.js
  src/components/commons/Layout/NavBar.tsx
  src/components/commons/Layout/findTripylerBanner.tsx
  src/components/commons/MainBanner.tsx
  src/components/commons/Modal/Block.js
  src/components/commons/Modal/Report.js
  src/components/commons/Modal/StyleModal.js
  src/components/main/AdverBanner.tsx
  src/components/main/Main.container.js
  src/components/main/ReviewBox.tsx
  src/components/main/TripylerBox.tsx
  src/components/profile/SideBar.jsx
  src/components/review/main/main.container.js
  src/components/review/main/main.styles.js
  src/components/review/write/write.container.js
  src/components/tripyler/list/ListBanner.jsx
  src/components/tripyler/list/ListBox.jsx
  src/components/tripyler/list/Platform.jsx
  src/components/tripyler/list/PlatformBox.tsx
  src/components/tripyler/list/list.container.js
  src/components/tripyler/list/list.style.js
  src/components/write/PlaceModal.tsx
  src/interfaces/write.ts
  src/styles/theme.ts
  src/styles/themeColor.ts
  tsconfig.json
Labels: design

#106 Fix: 빌드 오류 2차 해결
  package-lock.json
  package.json
  pages/404.tsx
  pages/_app.tsx
  pages/admin/index.tsx
  pages/findTripyler/[tripylerId]/edit/index.tsx
  pages/index.tsx
  pages/oauth/naver.js
  src/components/commons/Card/Preview/Preview.js
  src/components/contact/contact.container.tsx
  src/components/contact/contact.styles.ts
  src/components/detail/Images.tsx
  src/components/main/AdverBanner.tsx
  src/components/main/ReviewBanner.tsx
  src/components/main/ReviewBox.tsx
  src/components/main/TripylerBox.tsx
  src/components/tripyler/apply/ApplyForm.tsx
  src/components/tripyler/list/list.container.js
  src/components/tripyler/list/list.style.js
  src/components/write/IDModal.tsx
  src/components/write/ReviewStep2.tsx
  src/components/write/TripylerStep1.tsx
  src/components/write/TripylerStep3.tsx
  webpack.config.js
  yarn.lock
Labels: fix

#107 Design: 디자인 수정
  src/components/auth/profile/MyCollections/MyCollections.styles.js
  src/components/auth/profile/MyProfile/MyProfile.container.js
  src/components/auth/profile/MyProfile/MyProfile.styles.js
  src/components/auth/profile/Triplog/Triplog.styles.js
  src/components/commons/Card/Main/ReviewCard/ReviewMain.js
  src/components/commons/Modal/StyleModal.js
  src/components/review/main/main.container.js
  src/components/tripyler/list/ListBox.jsx
  webpack.config.js
Labels: design

#111 Design: 메인배너 모바일화면시 높이 수정
  src/components/commons/MainBanner.tsx
Labels: design
